
on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: lowlighter/metrics@latest
  with:
    # ... other options
    plugin_achievements: yes
    plugin_achievements_threshold: B       # Display achievements with rank B or higher
    plugin_achievements_secrets: yes       # Display unlocked secrets achievements
    plugin_achievements_ignored: octonaut  # Hide octonaut achievement
    plugin_achievements_limit: 0           # Display all unlocked achievement matching threshold and secrets params
    plugin_achievements_display: compact   # Use compact display